### ISSUE TITLE
Ошибка, когда у игрока используется только одна карта.

### ISSUE THREAD

**Issue by shiziksama** [pavel-grom/poker#1]
![image](https://user-images.githubusercontent.com/425254/47620462-1b04af00-daf3-11e8-8662-d788b13d03ac.png)

В такой ситуации он не может собрать флеш крест, потому что ему нужно использовать своего бубнового туза.

**Comment by pavel-grom** [comment]
Вероятно, что я плохо знаю правила техасского холдема, но вроде как выбирается лучшая **пятикарточная** комбинация из семи карт(2 игрока и 5 стола).
Можете объяснить почему ему обязательно нужно использовать своего туза?

**Comment by shiziksama** [comment]
Извините, я как то по глупому затупил(
