### ISSUE TITLE
Ошибка с определение flush

### ISSUE THREAD

**Issue by shiziksama** [pavel-grom/poker#2]
В этом случае должен победить player1, потому что он может собрать лучший флеш
![image](https://user-images.githubusercontent.com/425254/47646482-b5f59b80-db7c-11e8-891f-c2f1d570a359.png)

В этом случае они должны поделить стол поровну. Потому что они составляют полностью одинаковый флеш.
![image](https://user-images.githubusercontent.com/425254/47646505-c4dc4e00-db7c-11e8-9095-90e4669204be.png)

**Comment by pavel-grom** [comment]
Этот issue связан с этим https://github.com/pavel-grom/poker/issues/3, так что отвечу тут на оба.
Было два бага:
1. Стрит-флеш после недавнего рефакторинга ошибочно стал иметь старшинство обычного стрита.
Это я исправил вот тут https://github.com/pavel-grom/poker/commit/479f152f498aadaef4aa45459d5213f64b39feaa
2. Стрит-флеш ошибочно определялся когда имелись у игрока стрит и флеш, но с разными картами, эт я исправил тут https://github.com/pavel-grom/poker/commit/83417cba5beaf7b923592e5273fcb6e0781f793f

В общем как получалось:
У player0 - флеш, у player1 - стрит-флеш(ложный) старшинством(weight) равным обычному стриту.
Спасибо за замечания :+1:

**Comment by shiziksama** [comment]
@pavel-grom Спасибо за исправления. А не собираетесь сделать поддержку Омахи? Если нет, то я готов создать пулл реквест для такого.

**Comment by pavel-grom** [comment]
@shiziksama не собираюсь. На счет пулл реквеста я не против, лишь бы код был хотя бы не хуже моего)
К стати, до ваших issues я думал, что у меня с расчетом комбинаций всё более-менее норм, как же я ошибался)

**Comment by shiziksama** [comment]
@pavel-grom Рад помочь)
#5 Вот такие еще есть нюансы. Еще у меня появлялись мысли о программной части. Могу поделиться, если интересно. Могу просто создавать задачи на каждую такую штуку)
А могу просто молча делать pull-request-ы

**Comment by pavel-grom** [comment]
@shiziksama, а штуки какого рода, рефакторинг или новый функционал?
В общем не хочу лукавить, если мне чет покажется интересным, то могу сам сделать, если нет - ну вы поняли)
В любом случае буду рад критике и предложениям)

**Comment by shiziksama** [comment]
Если рады критике и предложениям, то хорошо) Это была проверка, не достал ли еще)
