### ISSUE TITLE
Стрит флеш определяет не совсем правильно

### ISSUE THREAD

**Issue by shiziksama** [pavel-grom/poker#3]
Написано, что стрит флеш крест, а в выводе участвует бубновая пятерка
![image](https://user-images.githubusercontent.com/425254/47646847-da05ac80-db7d-11e8-94bf-cc951c81f89b.png)

**Comment by pavel-grom** [comment]
Ответил вот тут https://github.com/pavel-grom/poker/issues/2#issuecomment-433888377
