### ISSUE TITLE
Старшинство стрита

### ISSUE THREAD

**Issue by shiziksama** [pavel-grom/poker#4]
![image](https://user-images.githubusercontent.com/425254/47663532-eef63600-dba5-11e8-8fc7-39e603ce2413.png)

Тут выигрывает player1, потому что стрит 23456 старше А2345

**Comment by pavel-grom** [comment]
поправил - https://github.com/pavel-grom/poker/commit/e296e23f9005c8c608ed75bf2117bfbd36ccc8a8
Думал, что этот вариант уже я тестировал, но нет)
