### ISSUE TITLE
Не совсем правильная функция в примере в readme

### ISSUE THREAD

**Issue by shiziksama** [pavel-grom/poker#5]
$randomizerCallback = function(array $cardsKeys): int {
    return array_rand($cardsKeys);
}
Такое не работает, потому что array_rand возвращает случайный ключ массива.

$randomizerCallback = function(array $cardsKeys): int {
			return $cardsKeys[array_rand($cardsKeys)];
		};

**Comment by pavel-grom** [comment]
Действительно, я даже и не проверял свой пример)
