### ISSUE TITLE
Определение каре

### ISSUE THREAD

**Issue by shiziksama** [pavel-grom/poker#6]
В этом случае выигрывает player0, потому что у него каре тузов
![image](https://user-images.githubusercontent.com/425254/47705089-31fbec00-dc2e-11e8-9cdf-45639d9edd5d.png)

**Comment by pavel-grom** [comment]
Поправил - https://github.com/pavel-grom/poker/commit/d4807ec4687c1e36723d75a258993bed3c6f3f58

**Comment by shiziksama** [comment]
@pavel-grom Спасибо.
