### ISSUE TITLE
Ошибка, когда у двои игроков фулхаус

### ISSUE THREAD

**Issue by shiziksama** [pavel-grom/poker#7]
Важно старшинство фулл хауза
![image](https://user-images.githubusercontent.com/425254/47723959-5374cc00-dc5e-11e8-9d29-f6b5e592ebd9.png)

ААА22  фул на тузах против 888222 фула на 88

**Comment by pavel-grom** [comment]
Пофиксил - https://github.com/pavel-grom/poker/commit/de8e506bf781e41ed18a3766bb061ac4a18ef251
Диву даюсь как можно так тупить)

**Comment by shiziksama** [comment]
Спасибо)
На самом деле всякое бывает. Я просто прогоняю тысячи игр, поэтому такое выплывает.

**Comment by shiziksama** [comment]
@pavel-grom А может зарезолвите те issue, которые выполнены?)

**Comment by shiziksama** [comment]
@pavel-grom А может зарезолвите те issue, которые выполнены?)
