### ISSUE TITLE
Обсуждение Омахи

### ISSUE THREAD

**Issue by shiziksama** [pavel-grom/poker#8]
По поводу омахи:
Для рассчета нам нужно переопределить количество возможных карт на руках.
И еще дополнительно нужно изменить логику подбора комбинаций. По сути расширить функционал CombinationDeterminant

Я предлагаю примерно такой вариант реализации:

```
$table=new Table();
$table->setGameType(new \Pagrom\Poker\Gametype\Holdem);

class Holdem extends Gametype interface{
	public $playerCardCount=2;
	public $tableCardCount =5;
	public function getCombinationDeterminant($tablecards,$playercards){
		return new \Pagrom\Poker\Combinations\HoldemCombinationDeterminant($tablecards,$playercards);
		}
}

public function determineCombinations(Table $table): void
    {
        foreach ($table->getPlayers() as $player) {
            $playerCombinationDeterminant = $table->getCombinationDeterminant($table->getCards(), $player->getCards());
            $combination = $playerCombinationDeterminant->getCombination();
            $player->setCombination($combination);
        }
    }
```
	
	
	
В HasCardsTrait есть обращение к константе static::MAX_CARDS_COUNT. Предлагаю это изменить как нибудь так static::$cardcount;
И эту переменную устанавливать во время установки типа игры для стола.
И устанавливать в игрока, во время прикрепления его к столу.
	
Если Вам нравится такой вариант реализации, то скоро я пришлю пулл реквест. Если же нет, то я готов изменить функционал как будет удобно Вам.

Возможно есть другой вариант, который больше впишется в Вашу концепцию.

**Comment by pavel-grom** [comment]
Мне всё норм, разве что можно Gametype передавать сразу в конструктор стола.
А то еще кто то посреди игры поменяет её тип)
